version: "3.0"

services:
  # 🔎 The Graph Node
  graph-node:
    image: graphprotocol/graph-node
    depends_on:
      - postgres
      - ipfs
    ports:
      - "8000:8000"   # GraphQL query endpoint
      - "8001:8001"   # Admin server (status/health)
      - "8020:8020"   # Subgraph deployment API
      - "8030:8030"   # JSON-RPC (optional)
      - "8040:8040"   # Prometheus metrics
    extra_hosts:
     - host.docker.internal:host-gateway
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: "http://ipfs:5001"
      ethereum: "dev:http://host.docker.internal:8545"
      GRAPH_LOG: info
    volumes:
      - graph-node-data:/data

  # 🗃️ PostgreSQL database
  postgres:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements",
        "-cmax_connections=200"
      ]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # 📦 IPFS node
  ipfs:
    image: ipfs/kubo:v0.17.0
    ports:
      - "5001:5001"  # IPFS API
      - "8080:8080"  # IPFS Gateway
    volumes:
      - ipfs-data:/data/ipfs

# 🧱 Declare all named volumes here
volumes:
  postgres-data:
  ipfs-data:
  graph-node-data:
